var child = [
  { 'dupe': false, 'type': 4, 'name': 'commemoration', 'dir': 'c0', 'linked': 2, 'url': 'https://mil.ru/commemoration/', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 2, 0, 0, 0 ], 'sig': 0xe73880f3 },
  { 'dupe': false, 'type': 4, 'name': 'economy', 'dir': 'c1', 'linked': 2, 'url': 'https://mil.ru/economy/', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 2, 0, 0, 0 ], 'sig': 0xa52f04d3 },
  { 'dupe': false, 'type': 4, 'name': 'fea', 'dir': 'c2', 'linked': 2, 'url': 'https://mil.ru/fea/', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 1, 0, 0, 0 ], 'sig': 0xbc17b578 },
  { 'dupe': false, 'type': 4, 'name': 'files', 'dir': 'c3', 'linked': 2, 'url': 'https://mil.ru/files/', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 2, 0, 0, 0 ], 'sig': 0x726229b9 },
  { 'dupe': false, 'type': 4, 'name': 'images', 'dir': 'c4', 'linked': 2, 'url': 'https://mil.ru/images/', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 4, 'issue_cnt': [ 1, 5, 0, 0, 0 ], 'sig': 0xda8f8015 },
  { 'dupe': false, 'type': 4, 'name': 'scripts', 'dir': 'c5', 'linked': 2, 'url': 'https://mil.ru/scripts/', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 2, 'issue_cnt': [ 0, 3, 0, 0, 0 ], 'sig': 0x21010c98 },
  { 'dupe': false, 'type': 4, 'name': 'sn', 'dir': 'c6', 'linked': 1, 'url': 'https://mil.ru/sn/', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 1, 0, 0, 0 ], 'sig': 0xe73c8097 },
  { 'dupe': false, 'type': 4, 'name': 'styles', 'dir': 'c7', 'linked': 2, 'url': 'https://mil.ru/styles/', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 3, 'issue_cnt': [ 0, 4, 0, 0, 0 ], 'sig': 0x21090c90 },
  { 'dupe': true, 'type': 32, 'name': 'armyforum.htm', 'dir': 'c8', 'linked': 2, 'url': 'https://mil.ru/armyforum.htm', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'commemoration.htm', 'dir': 'c9', 'linked': 2, 'url': 'https://mil.ru/commemoration.htm', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'dgo.htm', 'dir': 'c10', 'linked': 2, 'url': 'https://mil.ru/dgo.htm', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'index.htm', 'dir': 'c11', 'linked': 2, 'url': 'https://mil.ru/index.htm', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'memorial_cemetery.htm', 'dir': 'c12', 'linked': 2, 'url': 'https://mil.ru/memorial_cemetery.htm', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'projects.htm', 'dir': 'c13', 'linked': 2, 'url': 'https://mil.ru/projects.htm', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'site_map.htm', 'dir': 'c14', 'linked': 2, 'url': 'https://mil.ru/site_map.htm', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'state_services.htm', 'dir': 'c15', 'linked': 2, 'url': 'https://mil.ru/state_services.htm', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 }
];
