var child = [
  { 'dupe': false, 'type': 4, 'name': 'military', 'dir': 'c0', 'linked': 2, 'url': 'https://mil.ru/images/military/', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 3, 'issue_cnt': [ 1, 4, 0, 0, 0 ], 'sig': 0x2cff4313 },
  { 'dupe': true, 'type': 32, 'name': '3cvkg_vishnevsky.jpg', 'dir': 'c1', 'linked': 2, 'url': 'https://mil.ru/images/3cvkg_vishnevsky.jpg', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'banner_cska(1).png', 'dir': 'c2', 'linked': 2, 'url': 'https://mil.ru/images/banner_cska(1).png', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'ico02a.gif', 'dir': 'c3', 'linked': 1, 'url': 'https://mil.ru/images/ico02a.gif', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'logo_stopkoronavirus.svg', 'dir': 'c4', 'linked': 2, 'url': 'https://mil.ru/images/logo_stopkoronavirus.svg', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'mftb-logo-rus-2.jpg', 'dir': 'c5', 'linked': 2, 'url': 'https://mil.ru/images/mftb-logo-rus-2.jpg', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'ok.png', 'dir': 'c6', 'linked': 2, 'url': 'https://mil.ru/images/ok.png', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'redstar-baner.jpg', 'dir': 'c7', 'linked': 2, 'url': 'https://mil.ru/images/redstar-baner.jpg', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'rss15x15.png', 'dir': 'c8', 'linked': 2, 'url': 'https://mil.ru/images/rss15x15.png', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'rutube_logo_15.png', 'dir': 'c9', 'linked': 2, 'url': 'https://mil.ru/images/rutube_logo_15.png', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'telegram_logo_15x15.png', 'dir': 'c10', 'linked': 2, 'url': 'https://mil.ru/images/telegram_logo_15x15.png', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'twit15x15.png', 'dir': 'c11', 'linked': 2, 'url': 'https://mil.ru/images/twit15x15.png', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'vk1.png', 'dir': 'c12', 'linked': 2, 'url': 'https://mil.ru/images/vk1.png', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'yout15x15.png', 'dir': 'c13', 'linked': 2, 'url': 'https://mil.ru/images/yout15x15.png', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 }
];
