var child = [
  { 'dupe': true, 'type': 32, 'name': 'cal2.min.js', 'dir': 'c0', 'linked': 2, 'url': 'https://mil.ru/scripts/military/minified/cal2.min.js', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'jquery-1.7.2.min.js', 'dir': 'c1', 'linked': 2, 'url': 'https://mil.ru/scripts/military/minified/jquery-1.7.2.min.js', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'jquery.hoverIntent.min.js', 'dir': 'c2', 'linked': 2, 'url': 'https://mil.ru/scripts/military/minified/jquery.hoverIntent.min.js', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'mbMenu_menusettings.min.js', 'dir': 'c4', 'linked': 2, 'url': 'https://mil.ru/scripts/military/minified/mbMenu_menusettings.min.js', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'object.min.js', 'dir': 'c5', 'linked': 2, 'url': 'https://mil.ru/scripts/military/minified/object.min.js', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'ru.min.js', 'dir': 'c6', 'linked': 2, 'url': 'https://mil.ru/scripts/military/minified/ru.min.js', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'scripts.min.js', 'dir': 'c7', 'linked': 2, 'url': 'https://mil.ru/scripts/military/minified/scripts.min.js', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 },
  { 'dupe': true, 'type': 32, 'name': 'swfobjectsmall.min.js', 'dir': 'c8', 'linked': 2, 'url': 'https://mil.ru/scripts/military/minified/swfobjectsmall.min.js', 'fetched': false, 'error': 'Limits exceeded', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xded6f368 }
];
